# Generated by Django 6.0.4 on 2026-04-13 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0002_remove_ticket_assigned_to_ticketattendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Critica'), ('programada', 'Programada')], default='media', max_length=20),
        ),
        migrations.CreateModel(
            name='TicketPending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_pendings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pendencia de atendimento',
                'verbose_name_plural': 'Pendencias de atendimento',
                'ordering': ['-updated_at', '-id'],
            },
        ),
    ]
