# Generated by Django 6.0.4 on 2026-04-13 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0003_alter_ticket_priority_ticketpending'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=24, null=True, unique=True)),
                ('title', models.CharField(max_length=180)),
                ('kind', models.CharField(choices=[('fisica', 'Fisica'), ('digital', 'Digital')], default='fisica', max_length=20)),
                ('request_text', models.TextField()),
                ('status', models.CharField(choices=[('pendente_aprovacao', 'Pendente de aprovacao'), ('aprovada', 'Aprovada'), ('nao_aprovada', 'Nao aprovada'), ('parcialmente_entregue', 'Parcialmente entregue'), ('entregue', 'Entregue')], default='pendente_aprovacao', max_length=30)),
                ('requested_at', models.DateField(blank=True, null=True)),
                ('approved_at', models.DateField(blank=True, null=True)),
                ('partially_received_at', models.DateField(blank=True, null=True)),
                ('received_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Requisicao',
                'verbose_name_plural': 'Requisicoes',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RequisitionUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('status_to', models.CharField(blank=True, choices=[('pendente_aprovacao', 'Pendente de aprovacao'), ('aprovada', 'Aprovada'), ('nao_aprovada', 'Nao aprovada'), ('parcialmente_entregue', 'Parcialmente entregue'), ('entregue', 'Entregue')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisition_updates', to=settings.AUTH_USER_MODEL)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='chamados.requisition')),
            ],
            options={
                'verbose_name': 'Atualizacao de requisicao',
                'verbose_name_plural': 'Atualizacoes de requisicao',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
