# Generated by Django 6.0.4 on 2026-04-13 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0004_requisition_requisitionupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitionBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='requisitions/budgets/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_budgets', to='chamados.requisitionbudget')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='chamados.requisition')),
            ],
            options={
                'verbose_name': 'Orcamento de requisicao',
                'verbose_name_plural': 'Orcamentos de requisicao',
                'ordering': ['parent_budget_id', 'id'],
            },
        ),
    ]
