# Generated by Django 6.0.4 on 2026-04-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0005_requisitionbudget'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('name', models.CharField(max_length=200)),
                ('department', models.CharField(blank=True, default='', max_length=120)),
                ('legacy_id', models.PositiveIntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
