# Generated by Django 6.0.4 on 2026-04-16 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0007_add_marcelo_to_ti'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Starlink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('location', models.CharField(max_length=180)),
                ('email', models.EmailField(max_length=254)),
                ('password_encrypted', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('payment_method', models.CharField(choices=[('pix', 'Pix'), ('cartao', 'Cartao')], default='cartao', max_length=12)),
                ('card_final', models.CharField(blank=True, default='', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_starlinks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Starlink',
                'verbose_name_plural': 'Starlinks',
                'ordering': ['name', 'id'],
            },
        ),
    ]
