# Generated by Django 6.0.4 on 2026-04-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0008_starlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='starlink',
            name='payment_method',
            field=models.CharField(
                choices=[('pix', 'Pix'), ('cartao', 'Cartao')],
                default='cartao',
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name='starlink',
            name='card_final',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
    ]
