# Generated by Django 6.0.4 on 2026-04-16 14:55

from django.db import migrations, models


def convert_resolved_to_closed(apps, schema_editor):
    Ticket = apps.get_model('chamados', 'Ticket')
    TicketUpdate = apps.get_model('chamados', 'TicketUpdate')
    Ticket.objects.filter(status='resolvido').update(status='fechado')
    TicketUpdate.objects.filter(status_to='resolvido').update(status_to='fechado')


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0009_starlink_payment_method'),
    ]

    operations = [
        migrations.RunPython(convert_resolved_to_closed, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(
                choices=[
                    ('aberto', 'Aberto'),
                    ('em_atendimento', 'Em atendimento'),
                    ('aguardando_usuario', 'Aguardando usuario'),
                    ('fechado', 'Fechado'),
                ],
                default='aberto',
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name='ticketupdate',
            name='status_to',
            field=models.CharField(
                blank=True,
                choices=[
                    ('aberto', 'Aberto'),
                    ('em_atendimento', 'Em atendimento'),
                    ('aguardando_usuario', 'Aguardando usuario'),
                    ('fechado', 'Fechado'),
                ],
                max_length=25,
            ),
        ),
    ]
