# Generated by Django 6.0.4 on 2026-04-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0010_ticket_status_cleanup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starlink',
            name='password_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
    ]
