# Generated by Django 6.0.4 on 2026-04-16 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0011_starlink_password_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketAutoPauseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('attendance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auto_pause_review', to='chamados.ticketattendance')),
            ],
            options={
                'verbose_name': 'Revisao de pausa automatica',
                'verbose_name_plural': 'Revisoes de pausas automaticas',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
