# Generated by Django 6.0.4 on 2026-04-17 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_documentation_to_new_modules(apps, schema_editor):
    Documentation = apps.get_model('chamados', 'Documentation')
    DocumentEntry = apps.get_model('chamados', 'DocumentEntry')
    ContractEntry = apps.get_model('chamados', 'ContractEntry')

    for item in Documentation.objects.all():
        has_contract_data = bool(item.amount or item.contract_start or item.contract_end)
        if has_contract_data:
            ContractEntry.objects.create(
                name=item.name,
                notes=item.notes,
                amount=item.amount,
                validity_date=item.contract_end or item.contract_start,
                created_by_id=item.created_by_id,
                created_at=item.created_at,
                updated_at=item.updated_at,
            )
        else:
            DocumentEntry.objects.create(
                name=item.name,
                notes=item.notes,
                created_by_id=item.created_by_id,
                created_at=item.created_at,
                updated_at=item.updated_at,
            )


def reverse_migrate_documentation_to_new_modules(apps, schema_editor):
    Documentation = apps.get_model('chamados', 'Documentation')
    DocumentEntry = apps.get_model('chamados', 'DocumentEntry')
    ContractEntry = apps.get_model('chamados', 'ContractEntry')

    for item in DocumentEntry.objects.all():
        Documentation.objects.create(
            name=item.name,
            notes=item.notes,
            created_by_id=item.created_by_id,
            created_at=item.created_at,
            updated_at=item.updated_at,
        )

    for item in ContractEntry.objects.all():
        Documentation.objects.create(
            name=item.name,
            notes=item.notes,
            amount=item.amount,
            contract_end=item.validity_date,
            created_by_id=item.created_by_id,
            created_at=item.created_at,
            updated_at=item.updated_at,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0013_documentation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('notes', models.TextField(blank=True, default='')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='contracts/')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('validity_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, default='', max_length=80)),
                ('duration_value', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_unit', models.CharField(choices=[('meses', 'Meses'), ('anos', 'Anos')], default='meses', max_length=10)),
                ('payment_schedule', models.CharField(choices=[('mensal', 'Mensal'), ('pagamento_unico', 'Pagamento unico')], default='mensal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.RunPython(
            migrate_documentation_to_new_modules,
            reverse_migrate_documentation_to_new_modules,
        ),
        migrations.DeleteModel(
            name='Documentation',
        ),
    ]
