# Generated by Django 6.0.4 on 2026-04-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0014_contractentry_documententry_delete_documentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='documententry',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
