# Generated by Django 6.0.4 on 2026-04-23 12:10

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0022_requisitionbudget_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionbudget',
            name='approval_status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('nao_aprovado', 'Nao aprovado')], default='pendente', max_length=20),
        ),
        migrations.AddField(
            model_name='requisitionbudget',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='requisitionbudget',
            name='receipt_status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('parcial', 'Recebido parcial'), ('recebido', 'Recebido')], default='pendente', max_length=20),
        ),
        migrations.AddField(
            model_name='requisitionbudget',
            name='received_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='RequisitionBudgetHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('final_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('approval_status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('nao_aprovado', 'Nao aprovado')], default='pendente', max_length=20)),
                ('receipt_status', models.CharField(choices=[('pendente', 'Pendente'), ('parcial', 'Recebido parcial'), ('recebido', 'Recebido')], default='pendente', max_length=20)),
                ('received_quantity', models.PositiveIntegerField(default=0)),
                ('remaining_quantity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisition_budget_history_entries', to=settings.AUTH_USER_MODEL)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='chamados.requisitionbudget')),
            ],
            options={
                'verbose_name': 'Historico de orcamento de requisicao',
                'verbose_name_plural': 'Historicos de orcamento de requisicao',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
