# Generated by Django 6.0.4 on 2026-04-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0023_requisitionbudget_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionbudget',
            name='store_name',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='requisitionbudgethistory',
            name='store_name',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
    ]
