# Generated by Django 6.0.4 on 2026-04-23 19:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0024_requisitionbudget_store_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='freight_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
