# Generated by Django 6.0.4 on 2026-04-23 19:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0025_requisition_freight_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionbudget',
            name='freight_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='requisitionbudgethistory',
            name='freight_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
