# Generated by Django 6.0.4 on 2026-04-27 11:19

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0026_requisitionbudget_freight_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedServiceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=180)),
                ('company', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='completed_services/')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_completed_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Servico feito',
                'verbose_name_plural': 'Servicos feitos',
                'ordering': ['-updated_at', '-id'],
            },
        ),
    ]
