# Generated by Django 6.0.4 on 2026-04-27 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0027_completedserviceentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedServiceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='completed_services/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chamados.completedserviceentry')),
            ],
            options={
                'verbose_name': 'Anexo de servico feito',
                'verbose_name_plural': 'Anexos de servicos feitos',
                'ordering': ['id'],
            },
        ),
    ]
