# Generated by Django 6.0.4 on 2026-04-28 11:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0028_completedserviceattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedserviceentry',
            name='service_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
