# Generated by Django 6.0.4 on 2026-04-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0029_completedserviceentry_service_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractentry',
            name='payment_schedule',
            field=models.CharField(choices=[('mensal', 'Mensal'), ('anual', 'Anual'), ('pagamento_unico', 'Pagamento único')], default='mensal', max_length=20),
        ),
    ]
