# Generated by Django 6.0.4 on 2026-04-29 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0030_alter_contractentry_payment_schedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleWorkspaceEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=120)),
                ('last_name', models.CharField(blank=True, default='', max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(blank=True, default='', max_length=40)),
                ('last_sign_in', models.CharField(blank=True, default='', max_length=40)),
                ('email_usage', models.CharField(blank=True, default='', max_length=40)),
                ('drive_usage', models.CharField(blank=True, default='', max_length=40)),
                ('storage_used', models.CharField(blank=True, default='', max_length=40)),
                ('license_code', models.CharField(blank=True, default='', max_length=120)),
                ('last_imported_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imported_google_workspace_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Google Workspace',
                'verbose_name_plural': 'Emails Google Workspace',
                'ordering': ['email'],
            },
        ),
    ]
