# Generated by Django 6.0.4 on 2026-05-05 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0031_googleworkspaceemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='contracts/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chamados.contractentry')),
            ],
            options={
                'verbose_name': 'Anexo de contrato',
                'verbose_name_plural': 'Anexos de contratos',
                'ordering': ['id'],
            },
        ),
    ]
