# Generated by Django 6.0.4 on 2026-05-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0032_contractattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='failure_type',
            field=models.CharField(choices=[('software', 'Software'), ('equipamento', 'Equipamento'), ('hardware', 'Hardware'), ('humana', 'Humana'), ('na', 'N/A')], default='na', max_length=20),
        ),
    ]
