# Generated by Codex on 2026-05-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0033_ticket_failure_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionbudget',
            name='currency',
            field=models.CharField(choices=[('BRL', 'Real'), ('USD', 'Dolar')], default='BRL', max_length=3),
        ),
        migrations.AddField(
            model_name='requisitionbudgethistory',
            name='currency',
            field=models.CharField(choices=[('BRL', 'Real'), ('USD', 'Dolar')], default='BRL', max_length=3),
        ),
    ]
