# Generated by Codex on 2026-05-11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0034_requisitionbudget_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitionBudgetAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='requisitions/budget_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chamados.requisitionbudget')),
            ],
            options={
                'verbose_name': 'Anexo de orcamento de requisicao',
                'verbose_name_plural': 'Anexos de orcamento de requisicao',
                'ordering': ['uploaded_at', 'id'],
            },
        ),
    ]
