# Generated by Django 6.0.4 on 2026-05-12 19:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0035_requisitionbudgetattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collaborator_name', models.CharField(max_length=180)),
                ('collaborator_company', models.CharField(max_length=180)),
                ('collaborator_document', models.CharField(blank=True, default='', max_length=80)),
                ('collaborator_email', models.EmailField(blank=True, default='', max_length=254)),
                ('collaborator_phone', models.CharField(blank=True, default='', max_length=40)),
                ('equipment_type', models.CharField(max_length=120)),
                ('equipment_brand', models.CharField(blank=True, default='', max_length=120)),
                ('equipment_model', models.CharField(blank=True, default='', max_length=160)),
                ('equipment_serial', models.CharField(blank=True, default='', max_length=120)),
                ('patrimony_tag', models.CharField(blank=True, default='', max_length=80)),
                ('accessories', models.TextField(blank=True, default='')),
                ('loan_date', models.DateField(default=django.utils.timezone.localdate)),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('signed_document', models.FileField(blank=True, null=True, upload_to='equipment_loans/signed/')),
                ('documentation_ok', models.BooleanField(default=False)),
                ('documentation_ok_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_equipment_loans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Emprestimo de equipamento',
                'verbose_name_plural': 'Emprestimos de equipamentos',
                'ordering': ['-loan_date', '-id'],
            },
        ),
    ]
