# Generated by Django 6.0.4 on 2026-05-12 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0036_equipmentloan'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentLoanPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='equipment_loans/photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='chamados.equipmentloan')),
            ],
            options={
                'verbose_name': 'Foto de equipamento emprestado',
                'verbose_name_plural': 'Fotos de equipamentos emprestados',
                'ordering': ['id'],
            },
        ),
    ]
