# Generated by Django 6.0.4 on 2026-05-12 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0038_ticketcategory_ticket_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketFailureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de falha',
                'verbose_name_plural': 'Tipos de falha',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='category',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='failure_type',
            field=models.CharField(default='na', max_length=80),
        ),
        migrations.DeleteModel(
            name='TicketCategory',
        ),
    ]
