# Generated by Django 6.0.4 on 2026-05-13 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0040_equipmentloan_return'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketfailuretype',
            options={'ordering': ['name'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
    ]
