# Generated by Django 6.0.4 on 2026-05-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0041_alter_ticketfailuretype_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentloan',
            name='attendant_signature',
            field=models.FileField(blank=True, null=True, upload_to='equipment_loans/signatures/'),
        ),
    ]
