# Generated by Django 6.0.4 on 2026-05-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0043_phoneextension'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phoneextension',
            options={'ordering': ['department', 'name', 'extension'], 'verbose_name': 'Ramal', 'verbose_name_plural': 'Ramais'},
        ),
        migrations.AddField(
            model_name='phoneextension',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
