# Generated by Django 6.0.4 on 2026-05-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0044_alter_phoneextension_options_phoneextension_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneextension',
            name='email',
            field=models.TextField(blank=True, default=''),
        ),
    ]
