# Generated by Django 6.0.4 on 2026-05-14 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0046_fix_phoneextension_accents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentLoanAttendantSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('image', models.FileField(upload_to='equipment_loans/signature_profiles/')),
                ('authorization_password_hash', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_equipment_loan_signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assinatura autorizada para emprestimo',
                'verbose_name_plural': 'Assinaturas autorizadas para emprestimos',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='equipmentloan',
            name='attendant_signature_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_loans', to='chamados.equipmentloanattendantsignature'),
        ),
    ]
