# Generated by Django 6.0.4 on 2026-05-15 14:29

import django.db.models.deletion
from django.db import migrations, models


def copy_existing_equipment_to_items(apps, schema_editor):
    EquipmentLoan = apps.get_model('chamados', 'EquipmentLoan')
    EquipmentLoanItem = apps.get_model('chamados', 'EquipmentLoanItem')
    items = []
    for loan in EquipmentLoan.objects.all():
        items.append(
            EquipmentLoanItem(
                loan_id=loan.id,
                equipment_type=loan.equipment_type,
                equipment_brand=loan.equipment_brand,
                equipment_model=loan.equipment_model,
                equipment_serial=loan.equipment_serial,
                patrimony_tag=loan.patrimony_tag,
                accessories=loan.accessories,
            )
        )
    if items:
        EquipmentLoanItem.objects.bulk_create(items)


def remove_copied_equipment_items(apps, schema_editor):
    EquipmentLoanItem = apps.get_model('chamados', 'EquipmentLoanItem')
    EquipmentLoanItem.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0047_equipmentloanattendantsignature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentLoanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(max_length=120)),
                ('equipment_brand', models.CharField(blank=True, default='', max_length=120)),
                ('equipment_model', models.CharField(blank=True, default='', max_length=160)),
                ('equipment_serial', models.CharField(blank=True, default='', max_length=120)),
                ('patrimony_tag', models.CharField(blank=True, default='', max_length=80)),
                ('accessories', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='chamados.equipmentloan')),
            ],
            options={
                'verbose_name': 'Equipamento do emprestimo',
                'verbose_name_plural': 'Equipamentos do emprestimo',
                'ordering': ['id'],
            },
        ),
        migrations.RunPython(copy_existing_equipment_to_items, remove_copied_equipment_items),
    ]
