# Generated by Django 6.0.4 on 2026-05-15 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0048_equipmentloanitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('servers', 'Servidores'), ('switches', 'Switchs'), ('idface_turnstiles', 'IdFace + Catracas'), ('printers', 'Impressoras'), ('wifi', 'Wi-Fi'), ('monitoring', 'Zabbix & Grafana')], max_length=30)),
                ('ip_address', models.CharField(max_length=45, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=180)),
                ('manufacturer', models.CharField(blank=True, default='', max_length=180)),
                ('mac_address', models.CharField(blank=True, default='', max_length=80)),
                ('access', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_network_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IP',
                'verbose_name_plural': 'IPs',
                'ordering': ['category', 'ip_address'],
            },
        ),
    ]
