# Generated by Django 6.0.4 on 2026-05-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0050_seed_network_devices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('em_atendimento', 'Em atendimento'), ('aguardando_usuario', 'Aguardando usuario'), ('aguardando_autorizacao', 'Aguardando autorizacao'), ('fechado', 'Fechado')], default='aberto', max_length=25),
        ),
        migrations.AlterField(
            model_name='ticketupdate',
            name='status_to',
            field=models.CharField(blank=True, choices=[('aberto', 'Aberto'), ('em_atendimento', 'Em atendimento'), ('aguardando_usuario', 'Aguardando usuario'), ('aguardando_autorizacao', 'Aguardando autorizacao'), ('fechado', 'Fechado')], max_length=25),
        ),
    ]
