# Generated by Django 6.0.4 on 2026-05-21 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0051_alter_ticket_status_alter_ticketupdate_status_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentloanphoto',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='chamados.equipmentloanitem'),
        ),
    ]
