# Generated by Django 6.0.4 on 2026-05-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0053_uppercase_equipment_identifiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractentry',
            name='finished_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
