# Generated by Django 6.0.4 on 2026-05-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0054_contractentry_finished_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='starlink',
            name='antenna_code',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
