# Generated by Django 6.0.4 on 2026-05-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0056_rename_starlink_antenna_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiddenTicketFailureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized_name', models.CharField(max_length=120, unique=True)),
                ('display_name', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria oculta',
                'verbose_name_plural': 'Categorias ocultas',
                'ordering': ['display_name', 'normalized_name'],
            },
        ),
    ]
