# Generated by Django 6.0.4 on 2026-05-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0057_hiddenticketfailuretype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='futuradigitalentry',
            options={'ordering': ['-reference_month', '-id'], 'verbose_name': 'Futura Digital', 'verbose_name_plural': 'Futura Digital'},
        ),
        migrations.AddField(
            model_name='futuradigitalentry',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='futura_digital/documents/'),
        ),
        migrations.AlterField(
            model_name='futuradigitalentry',
            name='invoice',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='futuradigitalentry',
            name='name',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
    ]
