# Generated by Django 6.0.4 on 2026-05-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0058_alter_futuradigitalentry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='futuradigitalentry',
            name='bw_copies',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='futuradigitalentry',
            name='color_copies',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='futuradigitalentry',
            name='excess_copies',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
