# Generated by Django 6.0.4 on 2026-05-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0059_futuradigitalentry_bw_copies_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='futuradigitalentry',
            old_name='bw_copies',
            new_name='franchise_copies',
        ),
        migrations.AlterField(
            model_name='futuradigitalentry',
            name='franchise_copies',
            field=models.PositiveIntegerField(default=23000),
        ),
    ]
