# Generated by Django 6.0.4 on 2026-05-28 16:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0060_remove_futuradigitalentry_bw_copies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='futuradigitalentry',
            name='franchise_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('1610.00'), max_digits=12),
        ),
    ]
