# Generated by Django 6.0.4 on 2026-06-02 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0062_set_default_franchise_copies'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketUpdateAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ticket_updates/attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chamados.ticketupdate')),
            ],
            options={
                'verbose_name': 'Anexo de atualizacao de chamado',
                'verbose_name_plural': 'Anexos de atualizacoes de chamados',
                'ordering': ['id'],
            },
        ),
    ]
