# Generated by Django 6.0.4 on 2026-06-02 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0064_tiresponsibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('license_quantity', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_software_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Software',
                'verbose_name_plural': 'Softwares',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SoftwareLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(blank=True, default='', max_length=240)),
                ('linked_email', models.EmailField(blank=True, default='', max_length=254)),
                ('expiration_type', models.CharField(choices=[('indeterminado', 'Indeterminado'), ('expira_em', 'Prazo para expirar')], default='indeterminado', max_length=20)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, default='', max_length=80)),
                ('card_final', models.CharField(blank=True, default='', max_length=4)),
                ('assigned_user', models.CharField(blank=True, default='', max_length=180)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_software_licenses', to=settings.AUTH_USER_MODEL)),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='chamados.softwareasset')),
            ],
            options={
                'verbose_name': 'Licenca de software',
                'verbose_name_plural': 'Licencas de software',
                'ordering': ['software__name', 'assigned_user', 'linked_email', 'id'],
            },
        ),
    ]
