# Generated by Django 6.0.4 on 2026-06-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0065_softwareasset_softwarelicense'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentloanattendantsignature',
            name='signature_x_offset',
            field=models.IntegerField(default=0, help_text='Ajuste horizontal da imagem no PDF (positivo = direita, negativo = esquerda).'),
        ),
        migrations.AddField(
            model_name='equipmentloanattendantsignature',
            name='signature_y_offset',
            field=models.IntegerField(default=0, help_text='Ajuste vertical da imagem no PDF (positivo = cima, negativo = baixo).'),
        ),
    ]
