# Generated by Django 6.0.4 on 2026-06-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0066_equipmentloanattendantsignature_offsets'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentloan',
            name='attendant_signature_x_offset',
            field=models.IntegerField(default=0, help_text='Ajuste horizontal especifico desta assinatura no PDF.'),
        ),
        migrations.AddField(
            model_name='equipmentloan',
            name='attendant_signature_y_offset',
            field=models.IntegerField(default=0, help_text='Ajuste vertical especifico desta assinatura no PDF.'),
        ),
    ]
