# Generated by Django 6.0.4 on 2026-06-16 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0067_equipmentloan_attendant_signature_x_offset_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractAmountHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('new_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_amount_history_entries', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amount_history_entries', to='chamados.contractentry')),
            ],
            options={
                'verbose_name': 'Historico de valor de contrato',
                'verbose_name_plural': 'Historico de valores de contratos',
                'ordering': ['changed_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContractCustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('field_type', models.CharField(choices=[('texto', 'Texto'), ('numero', 'Numero'), ('sim_nao', 'Sim / Nao')], max_length=20)),
                ('value', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='chamados.contractentry')),
            ],
            options={
                'verbose_name': 'Campo personalizado de contrato',
                'verbose_name_plural': 'Campos personalizados de contratos',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
