# Generated by Django 6.0.4 on 2026-06-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0069_contractfieldhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications_enabled', models.BooleanField(default=False, verbose_name='Notificacoes ativadas')),
                ('provider', models.CharField(blank=True, choices=[('', 'Automatico'), ('wapi', 'W-API (w-api.app)'), ('webhook', 'Webhook personalizado')], default='', max_length=10, verbose_name='Provider')),
                ('group_jid', models.CharField(blank=True, default='', max_length=100, verbose_name='JID do grupo')),
                ('send_group_on_new_ticket', models.BooleanField(default=True, verbose_name='Enviar ao grupo em novo chamado')),
                ('template_new_ticket', models.CharField(blank=True, default='', help_text='Variaveis: {urgencia}, {solicitante}, {title}, {chamado}', max_length=500, verbose_name='Template mensagem novo chamado')),
                ('wapi_token', models.CharField(blank=True, default='', max_length=300, verbose_name='W-API Token')),
                ('wapi_instance', models.CharField(blank=True, default='', max_length=200, verbose_name='W-API Instance ID')),
                ('wapi_base_url', models.CharField(blank=True, default='', max_length=300, verbose_name='W-API Base URL')),
                ('webhook_url', models.CharField(blank=True, default='', max_length=500, verbose_name='Webhook URL')),
                ('webhook_token', models.CharField(blank=True, default='', max_length=300, verbose_name='Webhook Token (Bearer)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuracao WhatsApp',
                'verbose_name_plural': 'Configuracao WhatsApp',
            },
        ),
    ]
