# Generated by Django 6.0.5 on 2026-09-03 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0070_whatsapp_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketDeletionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.PositiveBigIntegerField()),
                ('ticket_title', models.CharField(max_length=180)),
                ('reason', models.TextField()),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_deletion_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exclusao de chamado',
                'verbose_name_plural': 'Exclusoes de chamados',
                'ordering': ['-deleted_at', '-id'],
            },
        ),
    ]
