from django.urls import path

from .views import (
    ClosedTicketsDataView,
    ContractListView,
    DocumentListView,
    TipListView,
    TicketAutoPauseReviewListView,
    InsumosView,
    RequisitionHubView,
    RequisitionSaveView,
    RequisitionStatusUpdateView,
    StarlinkDeleteView,
    StarlinkDetailView,
    StarlinkListView,
    StarlinkUpdateView,
    TicketCreateView,
    TicketDetailView,
    TicketDeleteView,
    TicketListView,
    TicketPendingCreateTicketView,
    TicketPendingDeleteView,
    TicketPendingListView,
    TicketTimerActionView,
)

urlpatterns = [
    path('', TicketListView.as_view(), name='chamados_list'),
    path('novo/', TicketCreateView.as_view(), name='chamados_new'),
    path('requisicoes/', RequisitionHubView.as_view(), name='chamados_requisicoes'),
    path('requisicoes/salvar/', RequisitionSaveView.as_view(), name='chamados_requisicoes_save'),
    path('requisicoes/<int:requisition_id>/status/', RequisitionStatusUpdateView.as_view(), name='chamados_requisicoes_status'),
    path('insumos/', InsumosView.as_view(), name='chamados_insumos'),
    path('documentos/', DocumentListView.as_view(), name='chamados_documentos'),
    path('contratos/', ContractListView.as_view(), name='chamados_contratos'),
    path('dicas/', TipListView.as_view(), name='chamados_dicas'),
    path('starlinks/', StarlinkListView.as_view(), name='chamados_starlinks'),
    path('starlinks/<int:starlink_id>/', StarlinkDetailView.as_view(), name='chamados_starlinks_detail'),
    path('starlinks/<int:starlink_id>/editar/', StarlinkUpdateView.as_view(), name='chamados_starlinks_update'),
    path('starlinks/<int:starlink_id>/apagar/', StarlinkDeleteView.as_view(), name='chamados_starlinks_delete'),
    path('pendencias/', TicketPendingListView.as_view(), name='chamados_pending_list'),
    path('pendencias/<int:pending_id>/apagar/', TicketPendingDeleteView.as_view(), name='chamados_pending_delete'),
    path('pendencias/<int:pending_id>/criar-chamado/', TicketPendingCreateTicketView.as_view(), name='chamados_pending_create_ticket'),
    path('fechados/dados/', ClosedTicketsDataView.as_view(), name='chamados_closed_data'),
    path('pausas-automaticas/', TicketAutoPauseReviewListView.as_view(), name='chamados_auto_pause_reviews'),
    path('<int:ticket_id>/excluir/', TicketDeleteView.as_view(), name='chamados_delete'),
    path('<int:ticket_id>/', TicketDetailView.as_view(), name='chamados_detail'),
    path('<int:ticket_id>/atendimento/', TicketTimerActionView.as_view(), name='chamados_action'),
]
