"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.4.
"""

from pathlib import Path
import os
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carrega variaveis de ambiente de um arquivo .env local, quando existir.
ENV_PATH = BASE_DIR / '.env'
if ENV_PATH.exists():
    for line in ENV_PATH.read_text(encoding='utf-8-sig').splitlines():
        raw = line.strip()
        if not raw or raw.startswith('#') or '=' not in raw:
            continue
        key, value = raw.split('=', 1)
        key = key.strip().lstrip('\ufeff')
        value = value.strip().strip('"').strip("'")
        if key:
            os.environ[key] = value


def _env_bool(name: str, default: bool = False) -> bool:
    raw = os.environ.get(name)
    if raw is None:
        return bool(default)
    return raw.strip().lower() in {'1', 'true', 'yes', 'on'}

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool('DEBUG', True)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = (os.environ.get('DJANGO_SECRET_KEY', '') or '').strip()
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-dev-insecure-key-change-in-production'
    else:
        raise ImproperlyConfigured('DJANGO_SECRET_KEY obrigatoria quando DEBUG=False.')

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'testserver']
extra_hosts = os.environ.get('EXTRA_ALLOWED_HOSTS', '')
if extra_hosts:
    for host in extra_hosts.split(','):
        normalized = host.strip()
        if normalized and normalized not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(normalized)

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'cofre',
    'chamados',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'users.context_processors.app_shell',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/
LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'America/Sao_Paulo'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
SERVE_STATIC_WITH_DJANGO = _env_bool('SERVE_STATIC_WITH_DJANGO', True)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
SERVE_MEDIA_WITH_DJANGO = _env_bool('SERVE_MEDIA_WITH_DJANGO', True)

# Security hardening
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = _env_bool('SESSION_COOKIE_SECURE', not DEBUG)
CSRF_COOKIE_SECURE = _env_bool('CSRF_COOKIE_SECURE', not DEBUG)
SECURE_SSL_REDIRECT = _env_bool('SECURE_SSL_REDIRECT', False)
SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '0') or '0')
SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', False)
SECURE_HSTS_PRELOAD = _env_bool('SECURE_HSTS_PRELOAD', False)

# Login/logout
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'chamados_list'
LOGOUT_REDIRECT_URL = 'login'
TI_GROUP_NAME = (os.environ.get('TI_GROUP_NAME', 'TI') or 'TI').strip()

# LDAP / Active Directory (SIDERTEC)
AUTHENTICATION_BACKENDS = [
    'users.auth_backend.ActiveDirectoryBackend',
    'django.contrib.auth.backends.ModelBackend',
]

AD_LDAP_SERVER_URI = os.environ.get('AD_LDAP_SERVER_URI', 'ldaps://192.168.22.8:636')
AD_LDAP_BASE_DN = os.environ.get('AD_LDAP_BASE_DN', 'dc=sidertec,dc=intra,dc=net')
AD_LDAP_BIND_DN = os.environ.get('AD_LDAP_BIND_DN', 'glpi_ldap@sidertec.intra.net')
AD_LDAP_BIND_PASSWORD = os.environ.get('AD_LDAP_BIND_PASSWORD', os.environ.get('ERP_LDAP_BIND_PASSWORD', ''))
AD_LDAP_USER_FILTER = os.environ.get(
    'AD_LDAP_USER_FILTER',
    '(&(objectCategory=person)(objectclass=user)(sAMAccountName=%(user)s))',
)
AD_LDAP_VALIDATE_CERT = _env_bool('AD_LDAP_VALIDATE_CERT', True)
AD_LDAP_CA_CERT_FILE = (os.environ.get('AD_LDAP_CA_CERT_FILE', '') or '').strip()
AD_LDAP_CONNECT_TIMEOUT = int(os.environ.get('AD_LDAP_CONNECT_TIMEOUT', '5') or '5')
AD_LDAP_USER_ATTR_MAP = {
    'username': 'sAMAccountName',
    'first_name': 'givenName',
    'last_name': 'sn',
    'email': 'mail',
}

# Cofre
VAULT_UNLOCK_SECONDS = int(os.environ.get('VAULT_UNLOCK_SECONDS', '120'))
VAULT_CLIPBOARD_CLEAR_SECONDS = int(os.environ.get('VAULT_CLIPBOARD_CLEAR_SECONDS', '15'))
VAULT_DEFAULT_PASSWORD = (os.environ.get('VAULT_DEFAULT_PASSWORD', '') or '').strip()
VAULT_ENCRYPTION_KEY = (os.environ.get('VAULT_ENCRYPTION_KEY', '') or '').strip()
VAULT_MAX_FAILED_ATTEMPTS = int(os.environ.get('VAULT_MAX_FAILED_ATTEMPTS', '5') or '5')
VAULT_LOCKOUT_SECONDS = int(os.environ.get('VAULT_LOCKOUT_SECONDS', '300') or '300')
VAULT_ALLOW_INSECURE_KEY_DERIVATION = _env_bool('VAULT_ALLOW_INSECURE_KEY_DERIVATION', DEBUG)

if not VAULT_ENCRYPTION_KEY and not VAULT_ALLOW_INSECURE_KEY_DERIVATION:
    raise ImproperlyConfigured(
        'VAULT_ENCRYPTION_KEY obrigatoria quando VAULT_ALLOW_INSECURE_KEY_DERIVATION=False.'
    )

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
