# Generated by Django 6.0.4 on 2026-04-10 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaultCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('account_username', models.CharField(blank=True, max_length=150)),
                ('password_encrypted', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_vault_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credencial do Cofre',
                'verbose_name_plural': 'Credenciais do Cofre',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='VaultSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_hash', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authorized_users', models.ManyToManyField(blank=True, related_name='vault_authorizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuracao do Cofre',
                'verbose_name_plural': 'Configuracoes do Cofre',
            },
        ),
    ]
