# Generated by Django 6.0.4 on 2026-04-10 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cofre', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vaultsettings',
            name='failed_unlock_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vaultsettings',
            name='lockout_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='VaultAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('unlock_success', 'Unlock sucesso'), ('unlock_failure', 'Unlock falha'), ('unlock_lockout', 'Unlock bloqueado temporariamente'), ('credential_created', 'Credencial criada'), ('credential_copied', 'Credencial copiada'), ('password_changed', 'Senha do cofre alterada'), ('access_list_changed', 'Lista de acesso alterada'), ('locked_manually', 'Cofre bloqueado manualmente')], max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('details', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vault_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='cofre.vaultcredential')),
            ],
            options={
                'verbose_name': 'Auditoria do Cofre',
                'verbose_name_plural': 'Auditoria do Cofre',
                'ordering': ['-created_at'],
            },
        ),
    ]
