# Generated by Django 6.0.4 on 2026-04-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cofre', '0002_vaultsettings_failed_unlock_attempts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaultauditlog',
            name='action',
            field=models.CharField(choices=[('unlock_success', 'Unlock sucesso'), ('unlock_failure', 'Unlock falha'), ('unlock_lockout', 'Unlock bloqueado temporariamente'), ('credential_created', 'Credencial criada'), ('credential_updated', 'Credencial atualizada'), ('credential_copied', 'Credencial copiada'), ('password_changed', 'Senha do cofre alterada'), ('access_list_changed', 'Lista de acesso alterada'), ('locked_manually', 'Cofre bloqueado manualmente')], max_length=64),
        ),
    ]
